name = "taz-comments"
main = "src/index.js"
compatibility_date = "2026-08-01"

[[d1_databases]]
binding = "DB"
database_name = "taz-comments"
database_id = "a3837a29-3437-4fad-971e-322e90fee563"

[vars]
ALLOWED_ORIGIN = "https://tazfm.fr"
NOTIFY_TO_EMAIL = "radiotousazimuts@gmail.com"
NOTIFY_FROM_EMAIL = "Tous Azimuts <notifications@tazfm.fr>"

# Secrets à définir avec `wrangler secret put <NOM>` (ne pas mettre ici) :
# - RESEND_API_KEY
# - MODERATION_SECRET (chaîne aléatoire longue, ex: `openssl rand -hex 32`)
